# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id_patient']},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dateInscription',
            new_name='date_inscription',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dateNaissance',
            new_name='date_naissance',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='groupeSanguin',
            new_name='groupe_sanguin',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='idPatient',
            new_name='id_patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='idUtilisateur',
            new_name='id_utilisateur',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='numeroSecuriteSociale',
            new_name='numero_securite_sociale',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='personneAContacter',
            new_name='personne_a_contacter',
        ),
    ]
