# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('natalite', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalite',
            name='id_patient',
            field=models.ForeignKey(db_column='id_patient', help_text='Patient représentant la mère / le parent', on_delete=django.db.models.deletion.CASCADE, related_name='natalites', to='patients.patient'),
        ),
    ]
