# Generated by Django 6.1 on 2026-08-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0003_chambre_statut_alter_chambre_type_chambre'),
        ('lit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lit',
            unique_together={('chambre', 'numero_lit')},
        ),
    ]
