# Generated by Django 6.1 on 2026-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_initial'),
        ('patients', '0002_initial'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(fields=('medecin', 'date_rdv', 'heure'), name='unique_medecin_date_heure_rdv'),
        ),
    ]
