# Generated by Django 6.0.8 on 2026-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('login', models.CharField(max_length=150, unique=True)),
                ('motDePasseHash', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('ADMINISTRATEUR', 'Administrateur'), ('MEDECIN', 'Medecin'), ('INFIRMIER', 'Infirmier')], max_length=20)),
                ('derniereConnexion', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
