# Generated by Django 6.0.8 on 2026-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motDePasseHash',
            field=models.CharField(max_length=255),
        ),
    ]
