# Generated by Django 6.1 on 2026-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_motdepassehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
