# Generated by Django 6.1 on 2026-09-10 13:38

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_historicalconsultation'),
        ('ordonnance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdonnance',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('reference', models.CharField(blank=True, db_index=True, help_text="Numéro ou référence unique de l'ordonnance (ex: ORD-20260825-001)", max_length=50)),
                ('date_ordonnance', models.DateField(default=django.utils.timezone.now, help_text='Date de la prescription')),
                ('observation', models.TextField(blank=True, help_text='Détail des médicaments, dosages et posologies', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultation', models.ForeignKey(blank=True, db_column='id_consultation', db_constraint=False, help_text='Consultation ayant donné lieu à la prescription', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consultation.consultation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ordonnance',
                'verbose_name_plural': 'historical Ordonnances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
