# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('idPersonnel', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('typePersonnel', models.CharField(choices=[('INFIRMIER', 'Infirmier(e)'), ('ADMINISTRATIF', 'Personnel Administratif'), ('TECHNICIEN', 'Technicien de Laboratoire / Radiologie'), ('PHARMACIEN', 'Pharmacien(ne)'), ('SAGE_FEMME', 'Sage-Femme'), ('AUTRE', 'Autre Personnel')], default='INFIRMIER', max_length=50)),
                ('poste', models.CharField(default='Personnel Soignant', max_length=100)),
                ('serviceHopital', models.CharField(default='Médecine Générale', max_length=100)),
                ('telephonePro', models.CharField(blank=True, max_length=20, null=True)),
                ('emailPro', models.EmailField(blank=True, max_length=254, null=True)),
                ('dateEmbauche', models.DateField()),
                ('idService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='services.service')),
            ],
        ),
    ]
