# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_rdv', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('CONFIRME', 'Confirmé'), ('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de consultation'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('ABSENT', 'Absent / Non honoré')], default='EN_ATTENTE', max_length=30)),
                ('medecin', models.ForeignKey(db_column='id_medecin', on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='medecin.medecin')),
                ('patient', models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_rdv', '-heure'],
            },
        ),
    ]
