# Generated by Django 6.1 on 2026-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('PROGRAMME', 'Programmé'), ('CONFIRME', 'Confirmé'), ('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de consultation'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('ABSENT', 'Absent / Non honoré')], default='EN_ATTENTE', max_length=30),
        ),
    ]
