# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortalite',
            fields=[
                ('id_deces', models.AutoField(primary_key=True, serialize=False)),
                ('date_deces', models.DateField()),
                ('heure_deces', models.TimeField(blank=True, null=True)),
                ('cause_deces', models.TextField(help_text='Cause principale ou diagnostiquée du décès')),
                ('lieu_deces', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('id_medecin', models.ForeignKey(blank=True, db_column='id_medecin', help_text='Médecin ayant constaté le décès', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_constates', to='medecin.medecin')),
            ],
            options={
                'verbose_name': 'Mortalité',
                'verbose_name_plural': 'Mortalités',
                'ordering': ['-date_deces', '-id_deces'],
            },
        ),
    ]
