# Generated by Django 6.1 on 2026-09-10 13:38

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('frais_consultation', '0001_initial'),
        ('medecin', '0004_indisponibilitemedecin_disponibilitemedecin'),
        ('patients', '0004_historicalpatient'),
        ('rendezvous', '0002_rendezvous_unique_medecin_date_heure_rdv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConsultation',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('date_cons', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure de la consultation')),
                ('symptomes', models.TextField(blank=True, help_text='Symptômes rapportés par le patient', null=True)),
                ('diagnostic', models.TextField(blank=True, help_text='Diagnostic médical établi', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observations ou conseils de suivi', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('frais', models.ForeignKey(blank=True, db_column='id_frais', db_constraint=False, help_text='Frais de consultation associés (optionnel)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frais_consultation.fraisconsultation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(blank=True, db_column='id_medecin', db_constraint=False, help_text='Médecin consultant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medecin.medecin')),
                ('patient', models.ForeignKey(blank=True, db_column='id_patient', db_constraint=False, help_text='Patient examiné', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
                ('rdv', models.ForeignKey(blank=True, db_column='id_rdv', db_constraint=False, help_text='Rendez-vous associé (optionnel)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rendezvous.rendezvous')),
            ],
            options={
                'verbose_name': 'historical Consultation',
                'verbose_name_plural': 'historical Consultations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
