# Generated by Django 6.1 on 2026-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('nomService', models.CharField(choices=[('MEDECINE_GENERALE', 'Médecine Générale'), ('URGENCES', 'Urgences & Soignants'), ('CARDIOLOGIE', 'Cardiologie'), ('PEDIATRIE', 'Pédiatrie'), ('GYNECOLOGIE', 'Gynécologie'), ('NEUROLOGIE', 'Neurologie'), ('DERMATOLOGIE', 'Dermatologie'), ('CHIRURGIE', 'Chirurgie Générale'), ('OPHTALMOLOGIE', 'Ophtalmologie'), ('PSYCHIATRIE', 'Psychiatrie'), ('RADIOLOGIE', 'Radiologie & Imagerie Médicale'), ('LABORATOIRE', 'Laboratoire & Analyses'), ('PHARMACIE', 'Pharmacie Centrale'), ('MATERNITE', 'Maternité'), ('ADMINISTRATION', 'Administration & Accueil'), ('REANIMATION', 'Réanimation'), ('AUTRE', 'Autre Service')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bureauLocalisation', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
