# Generated by Django 6.1 on 2026-08-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0002_medecin_matricule'),
        ('patients', '0004_alter_patient_numerosecuritesociale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natalite',
            fields=[
                ('id_nouveau_ne', models.AutoField(primary_key=True, serialize=False)),
                ('prenom_nouveau_ne', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_nouveau_ne', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField()),
                ('heure_naissance', models.TimeField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kg (ex: 3.25)', max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, help_text='Taille en cm (ex: 50.0)', max_digits=5, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('id_medecin', models.ForeignKey(blank=True, db_column='id_medecin', help_text='Médecin superviseur ou accoucheur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naissances_supervisees', to='medecin.medecin')),
                ('id_patient', models.ForeignKey(db_column='id_patient', help_text='Patient représentant la mère / le parent', on_delete=django.db.models.deletion.CASCADE, related_name='natalites', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Natalité',
                'verbose_name_plural': 'Natalités',
                'ordering': ['-date_naissance', '-id_nouveau_ne'],
            },
        ),
    ]
