# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id_service']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='bureauLocalisation',
            new_name='bureau_localisation',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='idService',
            new_name='id_service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nomService',
            new_name='nom_service',
        ),
    ]
