# Generated by Django 6.1 on 2026-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nomService',
            field=models.CharField(choices=[('MEDECINE_GENERALE', 'Médecine Générale'), ('URGENCES', 'Urgences & Soignants'), ('CARDIOLOGIE', 'Cardiologie'), ('PEDIATRIE', 'Pédiatrie'), ('GYNECOLOGIE', 'Gynécologie'), ('NEUROLOGIE', 'Neurologie'), ('DERMATOLOGIE', 'Dermatologie'), ('CHIRURGIE', 'Chirurgie Générale'), ('OPHTALMOLOGIE', 'Ophtalmologie'), ('PSYCHIATRIE', 'Psychiatrie'), ('RADIOLOGIE', 'Radiologie & Imagerie Médicale'), ('LABORATOIRE', 'Laboratoire & Analyses'), ('PHARMACIE', 'Pharmacie Centrale'), ('MATERNITE', 'Maternité'), ('ADMINISTRATION', 'Administration & Accueil'), ('REANIMATION', 'Réanimation'), ('AUTRE', 'Autre Service')], max_length=100, unique=True),
        ),
    ]
