# Generated by Django 6.1 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraisConsultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant des frais de consultation', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description ou détails des prestations incluses', null=True)),
                ('date_paiement', models.DateTimeField(blank=True, help_text='Date et heure effectives du règlement', null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Frais de Consultation',
                'verbose_name_plural': 'Frais de Consultations',
                'ordering': ['-id'],
            },
        ),
    ]
