# Generated by Django 6.1 on 2026-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('idMedecin', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(choices=[('GENERALISTE', 'Médecine Générale'), ('CARDIOLOGIE', 'Cardiologie'), ('PEDIATRIE', 'Pédiatrie'), ('GYNECOLOGIE', 'Gynécologie'), ('NEUROLOGIE', 'Neurologie'), ('DERMATOLOGIE', 'Dermatologie'), ('CHIRURGIE', 'Chirurgie'), ('OPHTALMOLOGIE', 'Ophtalmologie'), ('PSYCHIATRIE', 'Psychiatrie'), ('RADIOLOGIE', 'Radiologie')], default='GENERALISTE', max_length=50)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numeroOrdre', models.CharField(max_length=50, unique=True)),
                ('telephonePro', models.CharField(blank=True, max_length=20, null=True)),
                ('emailPro', models.EmailField(blank=True, max_length=254, null=True)),
                ('bureau', models.CharField(blank=True, max_length=50, null=True)),
                ('dateEmbauche', models.DateField()),
            ],
        ),
    ]
