# Generated by Django 6.1 on 2026-09-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_alter_medecin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibiliteMedecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(help_text="Date de début de l'indisponibilité")),
                ('date_fin', models.DateField(help_text="Date de fin de l'indisponibilité")),
                ('toute_la_journee', models.BooleanField(default=True, help_text='Si vrai, toute la plage de dates est bloquée')),
                ('heure_debut', models.TimeField(blank=True, help_text='Heure de début si indisponibilité partielle', null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text='Heure de fin si indisponibilité partielle', null=True)),
                ('motif', models.CharField(blank=True, help_text="Motif de l'absence (ex: Congé annuel, Formation, Garde)", max_length=255, null=True)),
                ('actif', models.BooleanField(default=True, help_text='Indique si cette indisponibilité est actuellement active')),
                ('medecin', models.ForeignKey(db_column='id_medecin', on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='medecin.medecin')),
            ],
            options={
                'verbose_name': 'Indisponibilité Médecin',
                'verbose_name_plural': 'Indisponibilités Médecins',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteMedecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0=Lundi, ..., 6=Dimanche)')),
                ('heure_debut', models.TimeField(default='08:30', help_text='Heure de début de consultation')),
                ('heure_fin', models.TimeField(default='16:30', help_text='Heure de fin de consultation')),
                ('pause_debut', models.TimeField(blank=True, default='12:30', help_text='Début de la pause déjeuner (optionnel)', null=True)),
                ('pause_fin', models.TimeField(blank=True, default='14:00', help_text='Fin de la pause déjeuner (optionnel)', null=True)),
                ('duree_creneau', models.IntegerField(default=45, help_text="Durée moyenne d'une consultation en minutes")),
                ('actif', models.BooleanField(default=True, help_text='Indique si le médecin consulte ce jour-là')),
                ('medecin', models.ForeignKey(db_column='id_medecin', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='medecin.medecin')),
            ],
            options={
                'verbose_name': 'Disponibilité Médecin',
                'verbose_name_plural': 'Disponibilités Médecins',
                'ordering': ['jour_semaine', 'heure_debut'],
                'unique_together': {('medecin', 'jour_semaine')},
            },
        ),
    ]
