# Generated by Django 6.1 on 2026-08-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('idChambre', models.AutoField(primary_key=True, serialize=False)),
                ('numero_chambre', models.IntegerField()),
                ('type_chambre', models.CharField(choices=[('INDIVIDUELLE', 'Chambre Individuelle'), ('DOUBLE', 'Chambre Double'), ('SUITE', 'Suite VIP'), ('REANIMATION', 'Soins Intensifs / Réanimation'), ('URGENCES', "Chambre d'Urgences"), ('AUTRE', 'Autre')], default='INDIVIDUELLE', max_length=50)),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='batiment.batiment')),
            ],
            options={
                'unique_together': {('batiment', 'numero_chambre')},
            },
        ),
    ]
