# Generated by Django 6.1 on 2026-08-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batiment', '0001_initial'),
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='idChambre',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='batiment',
            field=models.ForeignKey(db_column='id_batiment', on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='batiment.batiment'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='capacite',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de lits dans la chambre'),
        ),
    ]
