# Generated by Django 6.1 on 2026-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0002_alter_chambre_options_rename_idchambre_chambre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PARTIELLEMENT_OCCUPEE', 'Partiellement Occupée'), ('OCCUPEE', 'Occupée / Complète'), ('EN_NETTOYAGE', 'En nettoyage / Désinfection'), ('HORS_SERVICE', 'Hors Service / Maintenance')], default='DISPONIBLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_chambre',
            field=models.CharField(choices=[('INDIVIDUELLE', 'Chambre Individuelle'), ('DOUBLE', 'Chambre Double'), ('COMMUNE', 'Chambre Commune'), ('SUITE', 'Suite VIP'), ('REANIMATION', 'Soins Intensifs / Réanimation'), ('URGENCES', "Chambre d'Urgences"), ('AUTRE', 'Autre')], default='INDIVIDUELLE', max_length=50),
        ),
    ]
