# Generated by Django 6.1 on 2026-09-10 13:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordonnance', '0002_historicalordonnance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLigneOrdonnance',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('medicament', models.CharField(help_text='Nom du médicament, DCI ou spécialité (ex: Amoxicilline, Paracétamol)', max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='Dosage ou concentration (ex: 500 mg, 1 g, 250 mg/5 ml)', max_length=100, null=True)),
                ('forme', models.CharField(blank=True, help_text='Forme pharmaceutique (ex: Comprimé, Gélule, Sirop, Pommade, Injectable)', max_length=100, null=True)),
                ('posologie', models.CharField(help_text="Rythme et modalités d'administration (ex: 1 gélule 3 fois par jour)", max_length=255)),
                ('duree_traitement', models.CharField(blank=True, help_text='Durée de prise prescrite (ex: 5 jours, 10 jours, 1 mois renouvelable)', max_length=100, null=True)),
                ('quantite', models.PositiveIntegerField(default=1, help_text="Quantité prescrite / nombre d'unités ou boîtes")),
                ('instructions', models.TextField(blank=True, help_text='Recommandations cliniques particulières (ex: à prendre pendant les repas)', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordonnance', models.ForeignKey(blank=True, db_column='id_ordonnance', db_constraint=False, help_text='Ordonnance médicale à laquelle cette ligne est rattachée', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordonnance.ordonnance')),
            ],
            options={
                'verbose_name': "historical Ligne d'Ordonnance",
                'verbose_name_plural': "historical Lignes d'Ordonnances",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicament', models.CharField(help_text='Nom du médicament, DCI ou spécialité (ex: Amoxicilline, Paracétamol)', max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='Dosage ou concentration (ex: 500 mg, 1 g, 250 mg/5 ml)', max_length=100, null=True)),
                ('forme', models.CharField(blank=True, help_text='Forme pharmaceutique (ex: Comprimé, Gélule, Sirop, Pommade, Injectable)', max_length=100, null=True)),
                ('posologie', models.CharField(help_text="Rythme et modalités d'administration (ex: 1 gélule 3 fois par jour)", max_length=255)),
                ('duree_traitement', models.CharField(blank=True, help_text='Durée de prise prescrite (ex: 5 jours, 10 jours, 1 mois renouvelable)', max_length=100, null=True)),
                ('quantite', models.PositiveIntegerField(default=1, help_text="Quantité prescrite / nombre d'unités ou boîtes")),
                ('instructions', models.TextField(blank=True, help_text='Recommandations cliniques particulières (ex: à prendre pendant les repas)', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordonnance', models.ForeignKey(db_column='id_ordonnance', help_text='Ordonnance médicale à laquelle cette ligne est rattachée', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ordonnance.ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'Ordonnance",
                'verbose_name_plural': "Lignes d'Ordonnances",
                'ordering': ['id'],
            },
        ),
    ]
