# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['id_personnel']},
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='dateEmbauche',
            new_name='date_embauche',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='emailPro',
            new_name='email_pro',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='idPersonnel',
            new_name='id_personnel',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='idService',
            new_name='id_service',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='idUtilisateur',
            new_name='id_utilisateur',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='serviceHopital',
            new_name='service_hopital',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='telephonePro',
            new_name='telephone_pro',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='typePersonnel',
            new_name='type_personnel',
        ),
    ]
