# Generated by Django 6.1 on 2026-08-25 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lit', '0001_initial'),
        ('medecin', '0002_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure d'admission / d'entrée")),
                ('date_sortie', models.DateTimeField(blank=True, help_text="Date et heure de sortie de l'hôpital", null=True)),
                ('motif', models.TextField(blank=True, help_text="Motif de l'hospitalisation", null=True)),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée (Sortie)'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=30)),
                ('observation', models.TextField(blank=True, help_text='Observations médicales ou notes de suivi', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('lit', models.ForeignKey(blank=True, db_column='id_lit', help_text='Lit attribué au patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations', to='lit.lit')),
                ('medecin', models.ForeignKey(blank=True, db_column='id_medecin', help_text='Médecin traitant / responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations', to='medecin.medecin')),
                ('patient', models.ForeignKey(db_column='id_patient', help_text='Patient hospitalisé', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
                'ordering': ['-date_entree', '-id'],
            },
        ),
    ]
