# Generated by Django 6.1 on 2026-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('idBatiment', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nombre_chambre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
