# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batiment', '0002_alter_batiment_nombre_chambre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'ordering': ['id_batiment']},
        ),
        migrations.RenameField(
            model_name='batiment',
            old_name='idBatiment',
            new_name='id_batiment',
        ),
    ]
