# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_chambre', models.IntegerField()),
                ('type_chambre', models.CharField(choices=[('INDIVIDUELLE', 'Chambre Individuelle'), ('DOUBLE', 'Chambre Double'), ('COMMUNE', 'Chambre Commune'), ('SUITE', 'Suite VIP'), ('REANIMATION', 'Soins Intensifs / Réanimation'), ('URGENCES', "Chambre d'Urgences"), ('AUTRE', 'Autre')], default='INDIVIDUELLE', max_length=50)),
                ('capacite', models.PositiveIntegerField(default=1, help_text='Nombre de lits dans la chambre')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PARTIELLEMENT_OCCUPEE', 'Partiellement Occupée'), ('OCCUPEE', 'Occupée / Complète'), ('EN_NETTOYAGE', 'En nettoyage / Désinfection'), ('HORS_SERVICE', 'Hors Service / Maintenance')], default='DISPONIBLE', max_length=30)),
                ('batiment', models.ForeignKey(db_column='id_batiment', on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='batiment.batiment')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'unique_together': {('batiment', 'numero_chambre')},
            },
        ),
    ]
