# Generated by Django 6.1 on 2026-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='numero_chambre',
            field=models.IntegerField(default=0),
        ),
    ]
