# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0002_alter_chambre_numero_chambre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'ordering': ['id'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
    ]
