# Generated by Django 6.1 on 2026-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='nombre_chambre',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
