# Generated by Django 6.1 on 2026-09-10 13:38

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0001_initial'),
        ('lit', '0001_initial'),
        ('medecin', '0004_indisponibilitemedecin_disponibilitemedecin'),
        ('patients', '0004_historicalpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHospitalisation',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure d'admission / d'entrée")),
                ('date_sortie', models.DateTimeField(blank=True, help_text="Date et heure de sortie de l'hôpital", null=True)),
                ('motif', models.TextField(blank=True, help_text="Motif de l'hospitalisation", null=True)),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée (Sortie)'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=30)),
                ('observation', models.TextField(blank=True, help_text='Observations médicales ou notes de suivi', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lit', models.ForeignKey(blank=True, db_column='id_lit', db_constraint=False, help_text='Lit attribué au patient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lit.lit')),
                ('medecin', models.ForeignKey(blank=True, db_column='id_medecin', db_constraint=False, help_text='Médecin traitant / responsable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medecin.medecin')),
                ('patient', models.ForeignKey(blank=True, db_column='id_patient', db_constraint=False, help_text='Patient hospitalisé', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historical Hospitalisation',
                'verbose_name_plural': 'historical Hospitalisations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
