# Generated by Django 6.1 on 2026-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idPatient', models.AutoField(primary_key=True, serialize=False)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.CharField(max_length=255)),
                ('groupeSanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('numeroSecuriteSociale', models.CharField(blank=True, max_length=50, null=True)),
                ('personneAContacter', models.CharField(max_length=100)),
                ('dateInscription', models.DateField()),
            ],
        ),
    ]
