# Generated by Django 6.0.8 on 2026-08-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telephone',
        ),
    ]
