# Generated by Django 6.1 on 2026-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_email_remove_patient_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
