# Generated by Django 6.1 on 2026-08-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_datenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numeroSecuriteSociale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
