# Generated by Django 6.1 on 2026-08-25 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, help_text="Numéro ou référence unique de l'ordonnance (ex: ORD-20260825-001)", max_length=50, unique=True)),
                ('date_ordonnance', models.DateField(default=django.utils.timezone.now, help_text='Date de la prescription')),
                ('observation', models.TextField(blank=True, help_text='Détail des médicaments, dosages et posologies', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('consultation', models.ForeignKey(db_column='id_consultation', help_text='Consultation ayant donné lieu à la prescription', on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultation.consultation')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date_ordonnance', '-id'],
            },
        ),
    ]
