# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateNaissance',
            new_name='date_naissance',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idUser',
            new_name='id_user',
        ),
    ]
