# Generated by Django 6.0.8 on 2026-08-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_motdepassehash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('idMedecin', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(choices=[('GENERALISTE', 'Médecine Générale'), ('CARDIOLOGIE', 'Cardiologie'), ('PEDIATRIE', 'Pédiatrie'), ('GYNECOLOGIE', 'Gynécologie'), ('NEUROLOGIE', 'Neurologie'), ('DERMATOLOGIE', 'Dermatologie'), ('CHIRURGIE', 'Chirurgie'), ('OPHTALMOLOGIE', 'Ophtalmologie'), ('PSYCHIATRIE', 'Psychiatrie'), ('RADIOLOGIE', 'Radiologie')], default='GENERALISTE', max_length=50)),
                ('numeroOrdre', models.CharField(max_length=50, unique=True)),
                ('telephonePro', models.CharField(blank=True, max_length=20, null=True)),
                ('emailPro', models.EmailField(blank=True, max_length=254, null=True)),
                ('bureau', models.CharField(blank=True, max_length=50, null=True)),
                ('dateEmbauche', models.DateField()),
                ('idUtilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='users.user')),
            ],
        ),
    ]
