# Generated by Django 6.1 on 2026-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecin',
            options={'ordering': ['id_medecin']},
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='dateEmbauche',
            new_name='date_embauche',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='emailPro',
            new_name='email_pro',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='idMedecin',
            new_name='id_medecin',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='idUtilisateur',
            new_name='id_utilisateur',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='numeroOrdre',
            new_name='numero_ordre',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='telephonePro',
            new_name='telephone_pro',
        ),
    ]
