# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lit', models.CharField(blank=True, help_text='Identifiant ou numéro du lit (ex: Lit A, Lit 1, L-101-1)', max_length=20, null=True)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé'), ('RESERVE', 'Réservé'), ('EN_NETTOYAGE', 'En nettoyage / Désinfection'), ('HORS_SERVICE', 'Hors service / Maintenance')], default='DISPONIBLE', max_length=30)),
                ('chambre', models.ForeignKey(db_column='id_chambre', on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='chambre.chambre')),
            ],
            options={
                'verbose_name': 'Lit',
                'verbose_name_plural': 'Lits',
                'ordering': ['chambre', 'id'],
                'unique_together': {('chambre', 'numero_lit')},
            },
        ),
    ]
