# Generated by Django 6.1 on 2026-08-25 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frais_consultation', '0001_initial'),
        ('medecin', '0002_initial'),
        ('patients', '0002_initial'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_cons', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure de la consultation')),
                ('symptomes', models.TextField(blank=True, help_text='Symptômes rapportés par le patient', null=True)),
                ('diagnostic', models.TextField(blank=True, help_text='Diagnostic médical établi', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observations ou conseils de suivi', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('frais', models.ForeignKey(blank=True, db_column='id_frais', help_text='Frais de consultation associés (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='frais_consultation.fraisconsultation')),
                ('medecin', models.ForeignKey(blank=True, db_column='id_medecin', help_text='Médecin consultant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='medecin.medecin')),
                ('patient', models.ForeignKey(db_column='id_patient', help_text='Patient examiné', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('rdv', models.ForeignKey(blank=True, db_column='id_rdv', help_text='Rendez-vous associé (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='rendezvous.rendezvous')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_cons', '-id'],
            },
        ),
    ]
